### ISSUE TITLE
Audiobook support?

### ISSUE THREAD

**Issue by crogers2287** [compactd/compactd#33]
Any chance of adding audiobook support? Playback sync, bookmarking, and audio playback speed. This would be awesome. The only alternatives right now are plex and booksonic, plex is missing tons of features and booksonic is super buggy.

**Comment by vinz243** [comment]
While it would be an interesting feature to have I dont think it would be easy to implement given that the very nature of audiobooks is different from music. The whole interface is built for the artist/album/track flow, adding audiobook would mean writting an audiobook streaming app by itself integrated into  compactd, but since this isn't compactd goal, it would be better to create a whole another just for aubiobook streaming.
