### ISSUE TITLE
How does the search button works?

### ISSUE THREAD

**Issue by almet** [compactd/compactd#60]
There is a seach button at the top right, and when I click on it I'm able to enter some artist not present in my library, and I'm then displayed with a list of tracks for this artist, but I don't understand what I should do next with this?

Only individual tracks are displayed, and when I click on them I've got no feedback. Is this intended, or am I missing something?

Thanks!

**Comment by vinz243** [comment]
Hey, I'm not sure what button you are talking about. The standard procedure in 1.3.0 is to click on the Add item in the album list for an artist. In order to add a new artist you can search it (top left) then it should offer to add a new artist named after your search query. The search button I believe you are talking about is in the Downloads popup (and more like an add button)

**Comment by almet** [comment]
Yes, this is the « Downloads » button.

**Comment by almet** [comment]
Okay, so it seems related to gazelle integration #58. Closing.
